<a href="https://colab.research.google.com/github/JimKing100/nfl-test/blob/master/Actuals_Defense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
player_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/nfl-test/master/data-revised/players.csv')
defense_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/nfl-test/master/data-revised/defense.csv')
game_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/nfl-test/master/data-revised/game.csv')

In [3]:
player_df.head()

  player          first     last                 name position1
0     SF  San Francisco    49ers  San Francisco 49ers        DF
1    CHI        Chicago    Bears        Chicago Bears        DF
2    CIN     Cincinnati  Bengals   Cincinnati Bengals        DF
3    BUF        Buffalo    Bills        Buffalo Bills        DF
4    DEN         Denver  Broncos       Denver Broncos        DF

In [4]:
defense_df.head()

  team  week  2000  2001  2002  2003  ...  2014  2015  2016  2017  2018  2019
0  ARI     1     4     1   3.0     0  ...     2     4     6     9   5.0     5
1  ARI     2     7     2   5.0     1  ...     8    12    18     6   4.0     2
2  ARI     3     3    12   4.0     4  ...     3    24     8     1   7.0     4
3  ARI     4     3     6  13.0     3  ...     5     1     4     5   2.0     4
4  ARI     5     1     5  10.0     3  ...    16    13    13     3  20.0     1

[5 rows x 22 columns]

In [5]:
game_df.head()

   gid  seas  wk  day    v  ...       surf    ou  sprv  ptsv  ptsh
0    1  2000   1  SUN   SF  ...  AstroTurf  42.5   7.0    28    36
1    2  2000   1  SUN  JAC  ...      Grass  38.0 -10.0    27     7
2    3  2000   1  SUN  PHI  ...  AstroTurf  40.0   6.0    41    14
3    4  2000   1  SUN  NYJ  ...      Grass  36.0   2.5    20    16
4    5  2000   1  SUN  IND  ...      Grass  44.0  -3.0    27    14

[5 rows x 17 columns]

In [0]:
# Pull the stats to calculate the defense_db team points
def pull_stats(df1, df2, t, y, w, g):

    t_points = df1[y].loc[(df1['team']==t) & (df1['week']==g)].iloc[0]

    team_nameh = df2['h'].loc[(df2['seas']==int(y)) & (df2['wk']==w) & ((df2['v']==t) | (df2['h']==t))].iloc[0]
    team_namev = df2['v'].loc[(df2['seas']==int(y)) & (df2['wk']==w) & ((df2['v']==t) | (df2['h']==t))].iloc[0]

    if team_nameh == t:
        p_points = df2['ptsv'].loc[(df2['seas']==int(y)) & (df2['wk']==w) & ((df2['v']==t) | (df2['h']==t))].iloc[0]
    else:
        p_points = df2['ptsh'].loc[(df2['seas']==int(y)) & (df2['wk']==w) & ((df2['v']==t) | (df2['h']==t))].iloc[0]
    
    if p_points < 7:
        pa_points = 4
    if (p_points > 6) & (p_points < 14):
        pa_points = 3
    if (p_points > 13) & (p_points < 18):
        pa_points = 1
    if (p_points > 17) & (p_points < 28):
        pa_points = 0
    if (p_points > 27) & (p_points < 35): 
        pa_points = -1
    if (p_points > 34) & (p_points < 46):
        pa_points = -3
    if (p_points > 45):
        pa_points = -5

    d_points = t_points + pa_points

    return d_points

In [18]:
team = 'SF'
year = '2000'
week = 14
game = 13

weekly_dpoints = pull_stats(defense_df, game_df, team, year, week, game)
weekly_dpoints

19

In [8]:
player_df.head()

  player          first     last                 name position1
0     SF  San Francisco    49ers  San Francisco 49ers        DF
1    CHI        Chicago    Bears        Chicago Bears        DF
2    CIN     Cincinnati  Bengals   Cincinnati Bengals        DF
3    BUF        Buffalo    Bills        Buffalo Bills        DF
4    DEN         Denver  Broncos       Denver Broncos        DF

In [0]:
def add_row(df, p, f, l, n, pos, value_list):

    df = df.append({'player': p,
                    'first': f,
                    'last': l,
                    'name': n,
                    'position1': pos,
                    '2000-game1': value_list[0], 
                    '2000-game2': value_list[1],
                    '2000-game3': value_list[2], 
                    '2000-game4': value_list[3], 
                    '2000-game5': value_list[4], 
                    '2000-game6': value_list[5], 
                    '2000-game7': value_list[6], 
                    '2000-game8': value_list[7], 
                    '2000-game9': value_list[8],
                    '2000-game10': value_list[9],
                    '2000-game11': value_list[10],
                    '2000-game12': value_list[11],
                    '2000-game13': value_list[12],
                    '2000-game14': value_list[13],
                    '2000-game15': value_list[14],
                    '2000-game16': value_list[15],
                    '2001-game1': value_list[16], 
                    '2001-game2': value_list[17],
                    '2001-game3': value_list[18], 
                    '2001-game4': value_list[19], 
                    '2001-game5': value_list[20], 
                    '2001-game6': value_list[21], 
                    '2001-game7': value_list[22], 
                    '2001-game8': value_list[23], 
                    '2001-game9': value_list[24],
                    '2001-game10': value_list[25],
                    '2001-game11': value_list[26],
                    '2001-game12': value_list[27],
                    '2001-game13': value_list[28],
                    '2001-game14': value_list[29],
                    '2001-game15': value_list[30],
                    '2001-game16': value_list[31],
                    '2002-game1': value_list[32], 
                    '2002-game2': value_list[33],
                    '2002-game3': value_list[34], 
                    '2002-game4': value_list[35], 
                    '2002-game5': value_list[36], 
                    '2002-game6': value_list[37], 
                    '2002-game7': value_list[38], 
                    '2002-game8': value_list[39], 
                    '2002-game9': value_list[40],
                    '2002-game10': value_list[41],
                    '2002-game11': value_list[42],
                    '2002-game12': value_list[43],
                    '2002-game13': value_list[44],
                    '2002-game14': value_list[45],
                    '2002-game15': value_list[46],
                    '2002-game16': value_list[47],
                    '2003-game1': value_list[48], 
                    '2003-game2': value_list[49],
                    '2003-game3': value_list[50], 
                    '2003-game4': value_list[51], 
                    '2003-game5': value_list[52], 
                    '2003-game6': value_list[53], 
                    '2003-game7': value_list[54], 
                    '2003-game8': value_list[55], 
                    '2003-game9': value_list[56],
                    '2003-game10': value_list[57],
                    '2003-game11': value_list[58],
                    '2003-game12': value_list[59],
                    '2003-game13': value_list[60],
                    '2003-game14': value_list[61],
                    '2003-game15': value_list[62],
                    '2003-game16': value_list[63],
                    '2004-game1': value_list[64], 
                    '2004-game2': value_list[65],
                    '2004-game3': value_list[66], 
                    '2004-game4': value_list[67], 
                    '2004-game5': value_list[68], 
                    '2004-game6': value_list[69], 
                    '2004-game7': value_list[70], 
                    '2004-game8': value_list[71], 
                    '2004-game9': value_list[72],
                    '2004-game10': value_list[73],
                    '2004-game11': value_list[74],
                    '2004-game12': value_list[75],
                    '2004-game13': value_list[76],
                    '2004-game14': value_list[77],
                    '2004-game15': value_list[78],
                    '2004-game16': value_list[79],
                    '2005-game1': value_list[80], 
                    '2005-game2': value_list[81],
                    '2005-game3': value_list[82], 
                    '2005-game4': value_list[83], 
                    '2005-game5': value_list[84], 
                    '2005-game6': value_list[85], 
                    '2005-game7': value_list[86], 
                    '2005-game8': value_list[87], 
                    '2005-game9': value_list[88],
                    '2005-game10': value_list[89],
                    '2005-game11': value_list[90],
                    '2005-game12': value_list[91],
                    '2005-game13': value_list[92],
                    '2005-game14': value_list[93],
                    '2005-game15': value_list[94],
                    '2005-game16': value_list[95],
                    '2006-game1': value_list[96], 
                    '2006-game2': value_list[97],
                    '2006-game3': value_list[98], 
                    '2006-game4': value_list[99], 
                    '2006-game5': value_list[100], 
                    '2006-game6': value_list[101], 
                    '2006-game7': value_list[102], 
                    '2006-game8': value_list[103], 
                    '2006-game9': value_list[104],
                    '2006-game10': value_list[105],
                    '2006-game11': value_list[106],
                    '2006-game12': value_list[107],
                    '2006-game13': value_list[108],
                    '2006-game14': value_list[109],
                    '2006-game15': value_list[110],
                    '2006-game16': value_list[111],
                    '2007-game1': value_list[112], 
                    '2007-game2': value_list[113],
                    '2007-game3': value_list[114], 
                    '2007-game4': value_list[115], 
                    '2007-game5': value_list[116], 
                    '2007-game6': value_list[117], 
                    '2007-game7': value_list[118], 
                    '2007-game8': value_list[119], 
                    '2007-game9': value_list[120],
                    '2007-game10': value_list[121],
                    '2007-game11': value_list[122],
                    '2007-game12': value_list[123],
                    '2007-game13': value_list[124],
                    '2007-game14': value_list[125],
                    '2007-game15': value_list[126],
                    '2007-game16': value_list[127],
                    '2008-game1': value_list[128], 
                    '2008-game2': value_list[129],
                    '2008-game3': value_list[130], 
                    '2008-game4': value_list[131], 
                    '2008-game5': value_list[132], 
                    '2008-game6': value_list[133], 
                    '2008-game7': value_list[134], 
                    '2008-game8': value_list[135], 
                    '2008-game9': value_list[136],
                    '2008-game10': value_list[137],
                    '2008-game11': value_list[138],
                    '2008-game12': value_list[139],
                    '2008-game13': value_list[140],
                    '2008-game14': value_list[141],
                    '2008-game15': value_list[142],
                    '2008-game16': value_list[143],
                    '2009-game1': value_list[144], 
                    '2009-game2': value_list[145],
                    '2009-game3': value_list[146], 
                    '2009-game4': value_list[147], 
                    '2009-game5': value_list[148], 
                    '2009-game6': value_list[149], 
                    '2009-game7': value_list[150], 
                    '2009-game8': value_list[151], 
                    '2009-game9': value_list[152],
                    '2009-game10': value_list[25],
                    '2009-game11': value_list[26],
                    '2009-game12': value_list[27],
                    '2009-game13': value_list[28],
                    '2009-game14': value_list[29],
                    '2009-game15': value_list[30],
                    '2009-game16': value_list[31],
                    '2010-game1': value_list[0], 
                    '2010-game2': value_list[1],
                    '2010-game3': value_list[2], 
                    '2010-game4': value_list[3], 
                    '2010-game5': value_list[4], 
                    '2010-game6': value_list[5], 
                    '2010-game7': value_list[6], 
                    '2010-game8': value_list[7], 
                    '2010-game9': value_list[8],
                    '2010-game10': value_list[9],
                    '2010-game11': value_list[10],
                    '2010-game12': value_list[11],
                    '2010-game13': value_list[12],
                    '2010-game14': value_list[13],
                    '2010-game15': value_list[14],
                    '2010-game16': value_list[15],
                    '2011-game1': value_list[16], 
                    '2011-game2': value_list[17],
                    '2011-game3': value_list[18], 
                    '2011-game4': value_list[19], 
                    '2011-game5': value_list[20], 
                    '2011-game6': value_list[21], 
                    '2011-game7': value_list[22], 
                    '2011-game8': value_list[23], 
                    '2011-game9': value_list[24],
                    '2011-game10': value_list[25],
                    '2011-game11': value_list[26],
                    '2011-game12': value_list[27],
                    '2011-game13': value_list[28],
                    '2011-game14': value_list[29],
                    '2011-game15': value_list[30],
                    '2011-game16': value_list[31],
                    '2012-game1': value_list[0], 
                    '2012-game2': value_list[1],
                    '2012-game3': value_list[2], 
                    '2012-game4': value_list[3], 
                    '2012-game5': value_list[4], 
                    '2012-game6': value_list[5], 
                    '2012-game7': value_list[6], 
                    '2012-game8': value_list[7], 
                    '2012-game9': value_list[8],
                    '2012-game10': value_list[9],
                    '2012-game11': value_list[10],
                    '2012-game12': value_list[11],
                    '2012-game13': value_list[12],
                    '2012-game14': value_list[13],
                    '2012-game15': value_list[14],
                    '2012-game16': value_list[15],
                    '2013-game1': value_list[16], 
                    '2013-game2': value_list[17],
                    '2013-game3': value_list[18], 
                    '2013-game4': value_list[19], 
                    '2013-game5': value_list[20], 
                    '2013-game6': value_list[21], 
                    '2013-game7': value_list[22], 
                    '2013-game8': value_list[23], 
                    '2013-game9': value_list[24],
                    '2013-game10': value_list[25],
                    '2013-game11': value_list[26],
                    '2013-game12': value_list[27],
                    '2013-game13': value_list[28],
                    '2013-game14': value_list[29],
                    '2013-game15': value_list[30],
                    '2013-game16': value_list[31],
                    '2014-game1': value_list[0], 
                    '2014-game2': value_list[1],
                    '2014-game3': value_list[2], 
                    '2014-game4': value_list[3], 
                    '2014-game5': value_list[4], 
                    '2014-game6': value_list[5], 
                    '2014-game7': value_list[6], 
                    '2014-game8': value_list[7], 
                    '2014-game9': value_list[8],
                    '2014-game10': value_list[9],
                    '2014-game11': value_list[10],
                    '2014-game12': value_list[11],
                    '2014-game13': value_list[12],
                    '2014-game14': value_list[13],
                    '2014-game15': value_list[14],
                    '2014-game16': value_list[15],
                    '2015-game1': value_list[16], 
                    '2015-game2': value_list[17],
                    '2015-game3': value_list[18], 
                    '2015-game4': value_list[19], 
                    '2015-game5': value_list[20], 
                    '2015-game6': value_list[21], 
                    '2015-game7': value_list[22], 
                    '2015-game8': value_list[23], 
                    '2015-game9': value_list[24],
                    '2015-game10': value_list[25],
                    '2015-game11': value_list[26],
                    '2015-game12': value_list[27],
                    '2015-game13': value_list[28],
                    '2015-game14': value_list[29],
                    '2015-game15': value_list[30],
                    '2015-game16': value_list[31],
                    '2016-game1': value_list[0], 
                    '2016-game2': value_list[1],
                    '2016-game3': value_list[2], 
                    '2016-game4': value_list[3], 
                    '2016-game5': value_list[4], 
                    '2016-game6': value_list[5], 
                    '2016-game7': value_list[6], 
                    '2016-game8': value_list[7], 
                    '2016-game9': value_list[8],
                    '2016-game10': value_list[9],
                    '2016-game11': value_list[10],
                    '2016-game12': value_list[11],
                    '2016-game13': value_list[12],
                    '2016-game14': value_list[13],
                    '2016-game15': value_list[14],
                    '2016-game16': value_list[15],
                    '2017-game1': value_list[16], 
                    '2017-game2': value_list[17],
                    '2017-game3': value_list[18], 
                    '2017-game4': value_list[19], 
                    '2017-game5': value_list[20], 
                    '2017-game6': value_list[21], 
                    '2017-game7': value_list[22], 
                    '2017-game8': value_list[23], 
                    '2017-game9': value_list[24],
                    '2017-game10': value_list[25],
                    '2017-game11': value_list[26],
                    '2017-game12': value_list[27],
                    '2017-game13': value_list[28],
                    '2017-game14': value_list[29],
                    '2017-game15': value_list[30],
                    '2017-game16': value_list[31],
                    '2018-game1': value_list[0], 
                    '2018-game2': value_list[1],
                    '2018-game3': value_list[2], 
                    '2018-game4': value_list[3], 
                    '2018-game5': value_list[4], 
                    '2018-game6': value_list[5], 
                    '2018-game7': value_list[6], 
                    '2018-game8': value_list[7], 
                    '2018-game9': value_list[8],
                    '2018-game10': value_list[9],
                    '2018-game11': value_list[10],
                    '2018-game12': value_list[11],
                    '2018-game13': value_list[12],
                    '2018-game14': value_list[13],
                    '2018-game15': value_list[14],
                    '2018-game16': value_list[15],
                    '2019-game1': value_list[16], 
                    '2019-game2': value_list[17],
                    '2019-game3': value_list[18], 
                    '2019-game4': value_list[19], 
                    '2019-game5': value_list[20], 
                    '2019-game6': value_list[21], 
                    '2019-game7': value_list[22], 
                    '2019-game8': value_list[23], 
                    '2019-game9': value_list[24],
                    '2019-game10': value_list[25],
                    '2019-game11': value_list[26],
                    '2019-game12': value_list[27],
                    '2019-game13': value_list[28],
                    '2019-game14': value_list[29],
                    '2019-game15': value_list[30],
                    '2019-game16': value_list[31]
                     }, ignore_index=True)
    
    return df

In [0]:
column_names = ['player',
                'first',
                'last',
                'name',
                'position1', 
                '2000-game1',
                '2000-game2',
                '2000-game3', 
                '2000-game4', 
                '2000-game5', 
                '2000-game6', 
                '2000-game7', 
                '2000-game8', 
                '2000-game9',
                '2000-game10',
                '2000-game11',
                '2000-game12',
                '2000-game13',
                '2000-game14',
                '2000-game15',
                '2000-game16',
                '2001-game1', 
                '2001-game2',
                '2001-game3', 
                '2001-game4', 
                '2001-game5', 
                '2001-game6', 
                '2001-game7', 
                '2001-game8', 
                '2001-game9',
                '2001-game10',
                '2001-game11',
                '2001-game12',
                '2001-game13',
                '2001-game14',
                '2001-game15',
                '2001-game16',
                '2002-game1',
                '2002-game2',
                '2002-game3', 
                '2002-game4', 
                '2002-game5', 
                '2002-game6', 
                '2002-game7', 
                '2002-game8', 
                '2002-game9',
                '2002-game10',
                '2002-game11',
                '2002-game12',
                '2002-game13',
                '2002-game14',
                '2002-game15',
                '2002-game16',
                '2003-game1', 
                '2003-game2',
                '2003-game3', 
                '2003-game4', 
                '2003-game5', 
                '2003-game6', 
                '2003-game7', 
                '2003-game8', 
                '2003-game9',
                '2003-game10',
                '2003-game11',
                '2003-game12',
                '2003-game13',
                '2003-game14',
                '2003-game15',
                '2003-game16',
                '2004-game1',
                '2004-game2',
                '2004-game3', 
                '2004-game4', 
                '2004-game5', 
                '2004-game6', 
                '2004-game7', 
                '2004-game8', 
                '2004-game9',
                '2004-game10',
                '2004-game11',
                '2004-game12',
                '2004-game13',
                '2004-game14',
                '2004-game15',
                '2004-game16',
                '2005-game1', 
                '2005-game2',
                '2005-game3', 
                '2005-game4', 
                '2005-game5', 
                '2005-game6', 
                '2005-game7', 
                '2005-game8', 
                '2005-game9',
                '2005-game10',
                '2005-game11',
                '2005-game12',
                '2005-game13',
                '2005-game14',
                '2005-game15',
                '2005-game16',
                '2006-game1',
                '2006-game2',
                '2006-game3', 
                '2006-game4', 
                '2006-game5', 
                '2006-game6', 
                '2006-game7', 
                '2006-game8', 
                '2006-game9',
                '2006-game10',
                '2006-game11',
                '2006-game12',
                '2006-game13',
                '2006-game14',
                '2006-game15',
                '2006-game16',
                '2007-game1', 
                '2007-game2',
                '2007-game3', 
                '2007-game4', 
                '2007-game5', 
                '2007-game6', 
                '2007-game7', 
                '2007-game8', 
                '2007-game9',
                '2007-game10',
                '2007-game11',
                '2007-game12',
                '2007-game13',
                '2007-game14',
                '2007-game15',
                '2007-game16',
                '2008-game1',
                '2008-game2',
                '2008-game3', 
                '2008-game4', 
                '2008-game5', 
                '2008-game6', 
                '2008-game7', 
                '2008-game8', 
                '2008-game9',
                '2008-game10',
                '2008-game11',
                '2008-game12',
                '2008-game13',
                '2008-game14',
                '2008-game15',
                '2008-game16',
                '2009-game1', 
                '2009-game2',
                '2009-game3', 
                '2009-game4', 
                '2009-game5', 
                '2009-game6', 
                '2009-game7', 
                '2009-game8', 
                '2009-game9',
                '2009-game10',
                '2009-game11',
                '2009-game12',
                '2009-game13',
                '2009-game14',
                '2009-game15',
                '2009-game16',
                '2010-game1',
                '2010-game2',
                '2010-game3', 
                '2010-game4', 
                '2010-game5', 
                '2010-game6', 
                '2010-game7', 
                '2010-game8', 
                '2010-game9',
                '2010-game10',
                '2010-game11',
                '2010-game12',
                '2010-game13',
                '2010-game14',
                '2010-game15',
                '2010-game16',
                '2011-game1', 
                '2011-game2',
                '2011-game3', 
                '2011-game4', 
                '2011-game5', 
                '2011-game6', 
                '2011-game7', 
                '2011-game8', 
                '2011-game9',
                '2011-game10',
                '2011-game11',
                '2011-game12',
                '2011-game13',
                '2011-game14',
                '2011-game15',
                '2011-game16',
                '2012-game1',
                '2012-game2',
                '2012-game3', 
                '2012-game4', 
                '2012-game5', 
                '2012-game6', 
                '2012-game7', 
                '2012-game8', 
                '2012-game9',
                '2012-game10',
                '2012-game11',
                '2012-game12',
                '2012-game13',
                '2012-game14',
                '2012-game15',
                '2012-game16',
                '2013-game1', 
                '2013-game2',
                '2013-game3', 
                '2013-game4', 
                '2013-game5', 
                '2013-game6', 
                '2013-game7', 
                '2013-game8', 
                '2013-game9',
                '2013-game10',
                '2013-game11',
                '2013-game12',
                '2013-game13',
                '2013-game14',
                '2013-game15',
                '2013-game16',
                '2014-game1',
                '2014-game2',
                '2014-game3', 
                '2014-game4', 
                '2014-game5', 
                '2014-game6', 
                '2014-game7', 
                '2014-game8', 
                '2014-game9',
                '2014-game10',
                '2014-game11',
                '2014-game12',
                '2014-game13',
                '2014-game14',
                '2014-game15',
                '2014-game16',
                '2015-game1', 
                '2015-game2',
                '2015-game3', 
                '2015-game4', 
                '2015-game5', 
                '2015-game6', 
                '2015-game7', 
                '2015-game8', 
                '2015-game9',
                '2015-game10',
                '2015-game11',
                '2015-game12',
                '2015-game13',
                '2015-game14',
                '2015-game15',
                '2015-game16',
                '2016-game1',
                '2016-game2',
                '2016-game3', 
                '2016-game4', 
                '2016-game5', 
                '2016-game6', 
                '2016-game7', 
                '2016-game8', 
                '2016-game9',
                '2016-game10',
                '2016-game11',
                '2016-game12',
                '2016-game13',
                '2016-game14',
                '2016-game15',
                '2016-game16',
                '2017-game1', 
                '2017-game2',
                '2017-game3', 
                '2017-game4', 
                '2017-game5', 
                '2017-game6', 
                '2017-game7', 
                '2017-game8', 
                '2017-game9',
                '2017-game10',
                '2017-game11',
                '2017-game12',
                '2017-game13',
                '2017-game14',
                '2017-game15',
                '2017-game16',
                '2018-game1',
                '2018-game2',
                '2018-game3', 
                '2018-game4', 
                '2018-game5', 
                '2018-game6', 
                '2018-game7', 
                '2018-game8', 
                '2018-game9',
                '2018-game10',
                '2018-game11',
                '2018-game12',
                '2018-game13',
                '2018-game14',
                '2018-game15',
                '2018-game16',
                '2019-game1',
                '2019-game2',
                '2019-game3', 
                '2019-game4', 
                '2019-game5', 
                '2019-game6', 
                '2019-game7', 
                '2019-game8', 
                '2019-game9',
                '2019-game10',
                '2019-game11',
                '2019-game12',
                '2019-game13',
                '2019-game14',
                '2019-game15',
                '2019-game16'
                 ]

player = 'SF'
first = 'San Francisco'
last = '49ers'
name = 'San Francisco 49ers'
position1 = 'DF'

team = 'SF'

final_df = pd.DataFrame(columns = column_names)
player_scores = []
bye = 0

for i in range(2000,2020):
    week = 0
    for j in range(1,17):
        year = i
        game = j
        week = week + 1

        if ((game_df['h'].loc[(game_df['seas']==year) & (game_df['wk']==week) & ((game_df['v']==team) | (game_df['h']==team))].empty) & (game_df['v'].loc[(game_df['seas']==year) &
           (game_df['wk']==week) & ((game_df['v']==team) | (game_df['h']==team))].empty)):
            week = week + 1
            score = pull_stats(defense_df, game_df, team, str(year), week, game)
        else:
            score = pull_stats(defense_df, game_df, team, str(year), week, game)

        #print(team, year, week, game, score)
        player_scores.append(score)

final_df = add_row(final_df, player, first, last, name, position1, player_scores)

In [36]:
final_df.head()

  player          first   last  ... 2019-game14 2019-game15 2019-game16
0     SF  San Francisco  49ers  ...         NaN         NaN         NaN

[1 rows x 325 columns]