<a href="https://colab.research.google.com/github/JimKing100/nfl-test/blob/master/Weekly_Scoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
qb_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/nfl-test/master/data/qb-2019-weekly.csv')
rec_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/nfl-test/master/data/rec-2019-weekly.csv')
rush_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/nfl-test/master/data/rush-2019-weekly.csv')

In [14]:
qb_df.head()

   Rk           Player Pos     Age  ...  Pass Sk Pass Sk Yds Pass Y/A Pass AY/A
0   1    Lamar Jackson  QB  22.244  ...        1           1    16.20     21.20
1   2     Dak Prescott  QB  26.041  ...        0           0    12.66     15.16
2   3   Robert Griffin  QB  29.208  ...        0           0     9.17     12.50
3   4  Patrick Mahomes  QB  23.356  ...        0           0    11.45     13.27
4   5     Kirk Cousins  QB  31.020  ...        1           1     9.80     11.80

[5 rows x 24 columns]

In [15]:
rec_df.head()

   Rk          Player Pos     Age  ... Rec Y/R Rec TD Rec Ctch% Rec Y/Tgt
0   1   Sammy Watkins  WR  26.086  ...   22.00      3    81.80%     18.00
1   2  Michael Gallup  WR  23.157  ...   22.57      0   100.00%     22.57
2   3       John Ross  WR  24.285  ...   22.57      2    58.30%     13.17
3   4  DeSean Jackson  WR  32.281  ...   19.25      2    88.90%     17.11
4   5  Marquise Brown  WR  22.096  ...   36.75      2    80.00%     29.40

[5 rows x 20 columns]

In [16]:
rush_df.head()

    Rk               Player Pos     Age  ... Rush Att Rush Yds Rush Y/A Rush TD
0  1.0          Marlon Mack  RB  23.185  ...     25.0    174.0     6.96     1.0
1  2.0  Christian McCaffrey  RB  23.093  ...     19.0    128.0     6.74     2.0
2  3.0       Saquon Barkley  RB  22.211  ...     11.0    120.0    10.91     0.0
3  4.0          Dalvin Cook  RB  24.029  ...     21.0    111.0     5.29     2.0
4  5.0          Mark Ingram  RB  29.261  ...     14.0    107.0     7.64     2.0

[5 rows x 17 columns]

In [0]:
def scoring(p, w):
  # Passing TD
  if p in qb_df['Player'].values:
      score1 = qb_df['Pass TD'].loc[(qb_df['Player']==p) & (qb_df['Week']==w)]
      pass_td = score1.iloc[0]
  else:
      pass_td = 0

  # Receiving TD
  if p in rec_df['Player'].values:
      score2 = rec_df['Rec TD'].loc[(rec_df['Player']==p) & (rec_df['Week']==w)]
      rec_td = score2.iloc[0]
  else:
      rec_td = 0

  # Rushing TD
  if p in rush_df['Player'].values:
      score3 = rush_df['Rush TD'].loc[(rush_df['Player']==p) & (rush_df['Week']==w)]
      rush_td = score3.iloc[0]
  else:
      rush_td = 0
  
  # Passing Yards
  if p in qb_df['Player'].values:
      score4 = qb_df['Pass Yds'].loc[(qb_df['Player']==p) & (qb_df['Week']==w)]
      pass_yds = score4.iloc[0]
  else:
      pass_yds = 0

  # Receiving Yards
  if p in rec_df['Player'].values:
      score5 = rec_df['Rec Yds'].loc[(rec_df['Player']==p) & (rec_df['Week']==w)]
      rec_yds = score5.iloc[0]
  else:
      rec_yds = 0

  # Rushing Yards
  if p in rush_df['Player'].values:
      score6 = rush_df['Rush Yds'].loc[(rush_df['Player']==p) & (rush_df['Week']==w)]
      rush_yds = score6.iloc[0]
  else:
      rush_yds = 0

  # Interceptions
  if p in qb_df['Player'].values:
      score7 = qb_df['Pass Int'].loc[(qb_df['Player']==p) & (qb_df['Week']==w)]
      qb_int = score7.iloc[0]
  else:
      qb_int = 0
  
  score = (pass_td * 4) + (rec_td * 6) + (rush_td * 6) + (pass_yds / 25) + (rec_yds / 10) + (rush_yds / 10) - (qb_int *2)
  return score

In [104]:
player = 'Lamar Jackson'
week = 1

week1_score = scoring(player, week)
week1_score

33.56