In [0]:
# Imports
import pandas as pd
import numpy as np

from sklearn.metrics import mean_absolute_error

In [0]:
# Load the raw data
w1_results_df = pd.read_csv('https://raw.githubusercontent.com/Lambda-School-Labs/nfl-fantasy-ds/metrics/data/combined-predictions/predictions-week1.csv')

In [32]:
w1_results_df.head()

    player    first      last  ... rank-cur rank-pred  rank-act
0  JK-2250     Jake   Kumerow  ...    329.0       1.0     322.0
1  TG-1950     Todd    Gurley  ...      7.0       2.0      43.0
2  SB-0212   Saquon   Barkley  ...      9.0       3.0      36.0
3  RW-3850  Russell    Wilson  ...     10.0       4.0       4.0
4  DP-2037      Dak  Prescott  ...     12.0       5.0       3.0

[5 rows x 13 columns]

In [44]:
for i in range(1, 18):

    filename = 'https://raw.githubusercontent.com/Lambda-School-Labs/nfl-fantasy-ds/metrics/data/combined-predictions/predictions-week' + str(i) + '.csv'
    
    week_cur = 'week' + str(i) + '-cur'
    week_pred = 'week' + str(i) + '-pred'
    week_act = 'week' + str(i) + '-act'

    results_df = pd.read_csv(filename)

    if i == 1:
        week_current = results_df['week1-cur'].tolist()
    else:
        week_list = results_df[week_cur].tolist()
        week_current = [((element / i) * (16 - i)) for element in week_list]

    week_pred = results_df[week_pred].tolist()
    week_act = results_df[week_act].tolist()

    week_pa_mae = mean_absolute_error(week_act, week_pred)
    print('MAE predicted vs actual week {0:2d} {1:3.2f}%'.format(i, week_pa_mae))

    week_ca_mae = mean_absolute_error(week_act, week_current)
    print('MAE current vs actual week {0:2d} {1:3.2f}%'.format(i, week_ca_mae), '\n')

MAE predicted vs actual week  1 36.09%
MAE current vs actual week  1 36.30%

MAE predicted vs actual week  2 32.87%
MAE current vs actual week  2 38.95%

MAE predicted vs actual week  3 29.44%
MAE current vs actual week  3 31.77%

MAE predicted vs actual week  4 27.63%
MAE current vs actual week  4 27.85%

MAE predicted vs actual week  5 25.58%
MAE current vs actual week  5 25.14%

MAE predicted vs actual week  6 23.25%
MAE current vs actual week  6 23.01%

MAE predicted vs actual week  7 21.96%
MAE current vs actual week  7 21.17%

MAE predicted vs actual week  8 20.57%
MAE current vs actual week  8 19.58%

MAE predicted vs actual week  9 18.03%
MAE current vs actual week  9 18.04%

MAE predicted vs actual week 10 16.12%
MAE current vs actual week 10 16.45%

MAE predicted vs actual week 11 14.16%
MAE current vs actual week 11 14.82%

MAE predicted vs actual week 12 12.52%
MAE current vs actual week 12 13.56%

MAE predicted vs actual week 13 11.00%
MAE current vs actual week 13 12.39%

MAE predicted vs actual week 14 9.04%
MAE current vs actual week 14 10.73%

MAE predicted vs actual week 15 7.07%
MAE current vs actual week 15 8.89%

MAE predicted vs actual week 16 5.20%
MAE current vs actual week 16 7.31%

MAE predicted vs actual week 17 2.99%
MAE current vs actual week 17 6.95%

In [36]:
w2_results_df = pd.read_csv('https://raw.githubusercontent.com/Lambda-School-Labs/nfl-fantasy-ds/metrics/data/combined-predictions/predictions-week2.csv')
w2_results_df.head()

    player     first      last  ... rank-cur rank-pred  rank-act
0  MB-4075  Marquise     Brown  ...      8.0       1.0     180.0
1  JJ-0587      Josh    Jacobs  ...     22.0       2.0      61.0
2  KM-3500     Kyler    Murray  ...     27.0       3.0      10.0
3  TG-1950      Todd    Gurley  ...     86.0       4.0      42.0
4  TM-2275     Terry  McLaurin  ...     31.0       5.0     104.0

[5 rows x 13 columns]